affinity: {}
applicationProdProperties:
  configmap:
    application-prod.properties: >
      # Minimal config (please refer production application.properties values)

      server.port=1601

      spring.output.ansi.enabled=ALWAYS


      spring.jpa.hibernate.ddl-auto=none


      spring.datasource.url=jdbc:mysql://my-release-mysql-primary.default.svc.cluster.local:3306/symplified


      spring.datasource.username=root


      spring.datasource.password=kalsym@123


      spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  volumeMount:
    - mountPath: /home/docker/Software/application-prod.properties
      name: catalogue-import-service-approd-vol
      subPath: application-prod.properties
  volumes:
    - configMap:
        name: catalogue-import-service-approd-cm
      name: catalogue-import-service-approd-vol
applicationProperties:
  configmap:
    application.properties: >
      # Default config (refrain from editting this config, please add in
      application-prod.properties below)

      spring.profiles.active=prod

      proj.name=catalogue-import-service

      build.version=@project.version@
  volumeMount:
    - mountPath: /home/docker/Software/application.properties
      name: catalogue-import-service-ap-vol
      subPath: application.properties
  volumes:
    - configMap:
        name: catalogue-import-service-ap-cm
      name: catalogue-import-service-ap-vol
autoscaling:
  enabled: false
  maxReplicas: 100
  minReplicas: 1
  targetCPUUtilizationPercentage: 80
fullnameOverride: ''
image:
  pullPolicy: Always
  repository: kalsym/catalogue-import-service
  tag: 0.0.1-SNAPSHOT
imagePullSecrets:
  - name: kalsym-docker-hub
ingress:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  className: ''
  enabled: true
  hosts:
    - host: api.symplified.it
      paths:
        - path: /catalogue-import-service/v1(/|$)(.*)
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - api.symplified.it
      secretName: secret-tls-it
logback:
  configmap:
    logback.xml: |-
      # Mininal config (please refer production logback.xml values)
      <?xml version="1.0" encoding="UTF-8"?>
      <configuration></configuration>   
  volumeMount:
    - mountPath: /home/docker/Software/logback.xml
      name: catalogue-import-service-lgb-vol
      subPath: logback.xml
  volumes:
    - configMap:
        name: catalogue-import-service-lgb-cm
      name: catalogue-import-service-lgb-vol
nameOverride: ''
nodeSelector: {}
podAnnotations: {}
podSecurityContext: {}
replicaCount: 1
resources: {}
securityContext: {}
service:
  port: 1601
  type: ClusterIP
serviceAccount:
  annotations: {}
  create: false
  name: ''
tolerations: []